/******************************************************************************
 * Copyright (c) 2013 - 2014, AllSeen Alliance. All rights reserved.
 *
 *    Permission to use, copy, modify, and/or distribute this software for any
 *    purpose with or without fee is hereby granted, provided that the above
 *    copyright notice and this permission notice appear in all copies.
 *
 *    THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL WARRANTIES
 *    WITH REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED WARRANTIES OF
 *    MERCHANTABILITY AND FITNESS. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR
 *    ANY SPECIAL, DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES
 *    WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS, WHETHER IN AN
 *    ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING OUT OF
 *    OR IN CONNECTION WITH THE USE OR PERFORMANCE OF THIS SOFTWARE.
 ******************************************************************************/

#ifndef CONTROL_GENERATED_H_
#define CONTROL_GENERATED_H_

#include <alljoyn.h>
#include <ActionWidget.h>
#include <PropertyWidget.h>
#include <ContainerWidget.h>
#include <LabelWidget.h>
#include <DialogWidget.h>
#include <HttpControl.h>
#include <Services_Common.h>

/**
 * Defines and objectPaths
 */
#define NUM_PRECEDING_OBJECTS NUM_PRE_CONTROLPANEL_OBJECTS

#define GET_WIDGET_VALUE_CASES \
case EN_TRI_ROOTCONTAINER_GET_VALUE: \
case DE_AT_TRI_ROOTCONTAINER_GET_VALUE: \
case EN_TRI_HEATPROPERTY_GET_VALUE: \
case DE_AT_TRI_HEATPROPERTY_GET_VALUE: \
case EN_TRI_LIGHTACTION_GET_VALUE: \
case DE_AT_TRI_LIGHTACTION_GET_VALUE: \
case EN_TRI_LIGHTCONFIRM_GET_VALUE: \
case DE_AT_TRI_LIGHTCONFIRM_GET_VALUE: \
case EN_TRI_AREYOUSURE_GET_VALUE: \
case DE_AT_TRI_AREYOUSURE_GET_VALUE: \


#define GET_WIDGET_ALL_VALUE_CASES \
case EN_TRI_ROOTCONTAINER_GET_ALL_VALUES: \
case DE_AT_TRI_ROOTCONTAINER_GET_ALL_VALUES: \
case EN_TRI_HEATPROPERTY_GET_ALL_VALUES: \
case DE_AT_TRI_HEATPROPERTY_GET_ALL_VALUES: \
case EN_TRI_LIGHTACTION_GET_ALL_VALUES: \
case DE_AT_TRI_LIGHTACTION_GET_ALL_VALUES: \
case EN_TRI_LIGHTCONFIRM_GET_ALL_VALUES: \
case DE_AT_TRI_LIGHTCONFIRM_GET_ALL_VALUES: \
case EN_TRI_AREYOUSURE_GET_ALL_VALUES: \
case DE_AT_TRI_AREYOUSURE_GET_ALL_VALUES: \


#define GET_ROOT_VALUE_CASES \
case TRI_ROOT_CONTROLPANEL_ROOTCONTAINER_GET_VALUE: \
case TRI_NOTIFICATION_ACTION_AREYOUSURE_GET_VALUE: \


#define GET_ROOT_ALL_VALUE_CASES \
case TRI_ROOT_CONTROLPANEL_ROOTCONTAINER_GET_ALL_VALUES: \
case TRI_NOTIFICATION_ACTION_AREYOUSURE_GET_ALL_VALUES: \


#define SET_VALUE_CASES \
case TRI_ROOT_CONTROLPANEL_ROOTCONTAINER_SET_VALUE: \
case EN_TRI_ROOTCONTAINER_SET_VALUE: \
case DE_AT_TRI_ROOTCONTAINER_SET_VALUE: \
case EN_TRI_HEATPROPERTY_SET_VALUE: \
case DE_AT_TRI_HEATPROPERTY_SET_VALUE: \
case EN_TRI_LIGHTACTION_SET_VALUE: \
case DE_AT_TRI_LIGHTACTION_SET_VALUE: \
case EN_TRI_LIGHTCONFIRM_SET_VALUE: \
case DE_AT_TRI_LIGHTCONFIRM_SET_VALUE: \
case TRI_NOTIFICATION_ACTION_AREYOUSURE_SET_VALUE: \
case EN_TRI_AREYOUSURE_SET_VALUE: \
case DE_AT_TRI_AREYOUSURE_SET_VALUE: \


#define ACTION_CASES \
case EN_TRI_LIGHTACTION_EXEC: \
case DE_AT_TRI_LIGHTACTION_EXEC: \
case EN_TRI_LIGHTCONFIRM_EXEC_ACTION1: \
case EN_TRI_LIGHTCONFIRM_EXEC_ACTION2: \
case EN_TRI_LIGHTCONFIRM_EXEC_ACTION3: \
case DE_AT_TRI_LIGHTCONFIRM_EXEC_ACTION1: \
case DE_AT_TRI_LIGHTCONFIRM_EXEC_ACTION2: \
case DE_AT_TRI_LIGHTCONFIRM_EXEC_ACTION3: \
case EN_TRI_AREYOUSURE_EXEC_ACTION1: \
case EN_TRI_AREYOUSURE_EXEC_ACTION2: \
case EN_TRI_AREYOUSURE_EXEC_ACTION3: \
case DE_AT_TRI_AREYOUSURE_EXEC_ACTION1: \
case DE_AT_TRI_AREYOUSURE_EXEC_ACTION2: \
case DE_AT_TRI_AREYOUSURE_EXEC_ACTION3: \


#define GET_URL_CASES \


#define CONTROLPANELAPPOBJECTS     {  TriRootContainerObjectPath, ControlPanelInterfaces  }, \
    {  enTriRootContainerObjectPath, ContainerInterfaces  }, \
    {  de_ATTriRootContainerObjectPath, ContainerInterfaces  }, \
    {  enTriHeatPropertyObjectPath, PropertyInterfaces  }, \
    {  de_ATTriHeatPropertyObjectPath, PropertyInterfaces  }, \
    {  enTriLightActionObjectPath, ActionInterfaces  }, \
    {  de_ATTriLightActionObjectPath, ActionInterfaces  }, \
    {  enTriLightConfirmObjectPath, DialogInterfaces  }, \
    {  de_ATTriLightConfirmObjectPath, DialogInterfaces  }, \
    {  TriAreYouSureObjectPath, NotificationActionInterfaces  }, \
    {  enTriAreYouSureObjectPath, DialogInterfaces  }, \
    {  de_ATTriAreYouSureObjectPath, DialogInterfaces  }, \


#define CONTROLPANELANNOUNCEOBJECTS     {  TriRootContainerObjectPath, ControlPanelInterfaces  }, \


#define MAX_NUM_LANGUAGES 2

#define NUM_CONTROLPANEL_OBJECTS 12

#define TRI_MYLANGUAGES_EN 0
#define TRI_MYLANGUAGES_DE_AT 1

#define TRI_ROOT_CONTROLPANEL_ROOTCONTAINER_GET_VALUE                  AJ_APP_MESSAGE_ID(0 + NUM_PRECEDING_OBJECTS, 0, AJ_PROP_GET)
#define TRI_ROOT_CONTROLPANEL_ROOTCONTAINER_SET_VALUE                  AJ_APP_MESSAGE_ID(0 + NUM_PRECEDING_OBJECTS, 0, AJ_PROP_SET)
#define TRI_ROOT_CONTROLPANEL_ROOTCONTAINER_GET_ALL_VALUES             AJ_APP_MESSAGE_ID(0 + NUM_PRECEDING_OBJECTS, 0, AJ_PROP_GET_ALL)
#define TRI_ROOT_CONTROLPANEL_ROOTCONTAINER_VERSION_PROPERTY           AJ_APP_PROPERTY_ID(0 + NUM_PRECEDING_OBJECTS, 1, 0)

#define EN_TRI_ROOTCONTAINER_GET_VALUE                  AJ_APP_MESSAGE_ID(1 + NUM_PRECEDING_OBJECTS, 0, AJ_PROP_GET)
#define EN_TRI_ROOTCONTAINER_SET_VALUE                  AJ_APP_MESSAGE_ID(1 + NUM_PRECEDING_OBJECTS, 0, AJ_PROP_SET)
#define EN_TRI_ROOTCONTAINER_GET_ALL_VALUES             AJ_APP_MESSAGE_ID(1 + NUM_PRECEDING_OBJECTS, 0, AJ_PROP_GET_ALL)
#define EN_TRI_ROOTCONTAINER_VERSION_PROPERTY           AJ_APP_PROPERTY_ID(1 + NUM_PRECEDING_OBJECTS, 1, 0)
#define EN_TRI_ROOTCONTAINER_STATES_PROPERTY            AJ_APP_PROPERTY_ID(1 + NUM_PRECEDING_OBJECTS, 1, 1)
#define EN_TRI_ROOTCONTAINER_OPTPARAMS_PROPERTY         AJ_APP_PROPERTY_ID(1 + NUM_PRECEDING_OBJECTS, 1, 2)
#define EN_TRI_ROOTCONTAINER_SIGNAL_PROPERTIES_CHANGED  AJ_APP_MESSAGE_ID(1 + NUM_PRECEDING_OBJECTS, 1, 3)

#define DE_AT_TRI_ROOTCONTAINER_GET_VALUE                  AJ_APP_MESSAGE_ID(2 + NUM_PRECEDING_OBJECTS, 0, AJ_PROP_GET)
#define DE_AT_TRI_ROOTCONTAINER_SET_VALUE                  AJ_APP_MESSAGE_ID(2 + NUM_PRECEDING_OBJECTS, 0, AJ_PROP_SET)
#define DE_AT_TRI_ROOTCONTAINER_GET_ALL_VALUES             AJ_APP_MESSAGE_ID(2 + NUM_PRECEDING_OBJECTS, 0, AJ_PROP_GET_ALL)
#define DE_AT_TRI_ROOTCONTAINER_VERSION_PROPERTY           AJ_APP_PROPERTY_ID(2 + NUM_PRECEDING_OBJECTS, 1, 0)
#define DE_AT_TRI_ROOTCONTAINER_STATES_PROPERTY            AJ_APP_PROPERTY_ID(2 + NUM_PRECEDING_OBJECTS, 1, 1)
#define DE_AT_TRI_ROOTCONTAINER_OPTPARAMS_PROPERTY         AJ_APP_PROPERTY_ID(2 + NUM_PRECEDING_OBJECTS, 1, 2)
#define DE_AT_TRI_ROOTCONTAINER_SIGNAL_PROPERTIES_CHANGED  AJ_APP_MESSAGE_ID(2 + NUM_PRECEDING_OBJECTS, 1, 3)

#define EN_TRI_HEATPROPERTY_GET_VALUE                  AJ_APP_MESSAGE_ID(3 + NUM_PRECEDING_OBJECTS, 0, AJ_PROP_GET)
#define EN_TRI_HEATPROPERTY_SET_VALUE                  AJ_APP_MESSAGE_ID(3 + NUM_PRECEDING_OBJECTS, 0, AJ_PROP_SET)
#define EN_TRI_HEATPROPERTY_GET_ALL_VALUES             AJ_APP_MESSAGE_ID(3 + NUM_PRECEDING_OBJECTS, 0, AJ_PROP_GET_ALL)
#define EN_TRI_HEATPROPERTY_VERSION_PROPERTY           AJ_APP_PROPERTY_ID(3 + NUM_PRECEDING_OBJECTS, 1, 0)
#define EN_TRI_HEATPROPERTY_STATES_PROPERTY            AJ_APP_PROPERTY_ID(3 + NUM_PRECEDING_OBJECTS, 1, 1)
#define EN_TRI_HEATPROPERTY_OPTPARAMS_PROPERTY         AJ_APP_PROPERTY_ID(3 + NUM_PRECEDING_OBJECTS, 1, 2)
#define EN_TRI_HEATPROPERTY_SIGNAL_PROPERTIES_CHANGED  AJ_APP_MESSAGE_ID(3 + NUM_PRECEDING_OBJECTS, 1, 3)
#define EN_TRI_HEATPROPERTY_VALUE_PROPERTY             AJ_APP_PROPERTY_ID(3 + NUM_PRECEDING_OBJECTS, 1, 4)
#define EN_TRI_HEATPROPERTY_SIGNAL_VALUE_CHANGED       AJ_APP_MESSAGE_ID(3 + NUM_PRECEDING_OBJECTS, 1, 5)

#define DE_AT_TRI_HEATPROPERTY_GET_VALUE                  AJ_APP_MESSAGE_ID(4 + NUM_PRECEDING_OBJECTS, 0, AJ_PROP_GET)
#define DE_AT_TRI_HEATPROPERTY_SET_VALUE                  AJ_APP_MESSAGE_ID(4 + NUM_PRECEDING_OBJECTS, 0, AJ_PROP_SET)
#define DE_AT_TRI_HEATPROPERTY_GET_ALL_VALUES             AJ_APP_MESSAGE_ID(4 + NUM_PRECEDING_OBJECTS, 0, AJ_PROP_GET_ALL)
#define DE_AT_TRI_HEATPROPERTY_VERSION_PROPERTY           AJ_APP_PROPERTY_ID(4 + NUM_PRECEDING_OBJECTS, 1, 0)
#define DE_AT_TRI_HEATPROPERTY_STATES_PROPERTY            AJ_APP_PROPERTY_ID(4 + NUM_PRECEDING_OBJECTS, 1, 1)
#define DE_AT_TRI_HEATPROPERTY_OPTPARAMS_PROPERTY         AJ_APP_PROPERTY_ID(4 + NUM_PRECEDING_OBJECTS, 1, 2)
#define DE_AT_TRI_HEATPROPERTY_SIGNAL_PROPERTIES_CHANGED  AJ_APP_MESSAGE_ID(4 + NUM_PRECEDING_OBJECTS, 1, 3)
#define DE_AT_TRI_HEATPROPERTY_VALUE_PROPERTY             AJ_APP_PROPERTY_ID(4 + NUM_PRECEDING_OBJECTS, 1, 4)
#define DE_AT_TRI_HEATPROPERTY_SIGNAL_VALUE_CHANGED       AJ_APP_MESSAGE_ID(4 + NUM_PRECEDING_OBJECTS, 1, 5)

#define EN_TRI_LIGHTACTION_GET_VALUE                  AJ_APP_MESSAGE_ID(5 + NUM_PRECEDING_OBJECTS, 0, AJ_PROP_GET)
#define EN_TRI_LIGHTACTION_SET_VALUE                  AJ_APP_MESSAGE_ID(5 + NUM_PRECEDING_OBJECTS, 0, AJ_PROP_SET)
#define EN_TRI_LIGHTACTION_GET_ALL_VALUES             AJ_APP_MESSAGE_ID(5 + NUM_PRECEDING_OBJECTS, 0, AJ_PROP_GET_ALL)
#define EN_TRI_LIGHTACTION_VERSION_PROPERTY           AJ_APP_PROPERTY_ID(5 + NUM_PRECEDING_OBJECTS, 1, 0)
#define EN_TRI_LIGHTACTION_STATES_PROPERTY            AJ_APP_PROPERTY_ID(5 + NUM_PRECEDING_OBJECTS, 1, 1)
#define EN_TRI_LIGHTACTION_OPTPARAMS_PROPERTY         AJ_APP_PROPERTY_ID(5 + NUM_PRECEDING_OBJECTS, 1, 2)
#define EN_TRI_LIGHTACTION_SIGNAL_PROPERTIES_CHANGED  AJ_APP_MESSAGE_ID(5 + NUM_PRECEDING_OBJECTS, 1, 3)
#define EN_TRI_LIGHTACTION_EXEC                       AJ_APP_MESSAGE_ID(5 + NUM_PRECEDING_OBJECTS, 1, 4)

#define DE_AT_TRI_LIGHTACTION_GET_VALUE                  AJ_APP_MESSAGE_ID(6 + NUM_PRECEDING_OBJECTS, 0, AJ_PROP_GET)
#define DE_AT_TRI_LIGHTACTION_SET_VALUE                  AJ_APP_MESSAGE_ID(6 + NUM_PRECEDING_OBJECTS, 0, AJ_PROP_SET)
#define DE_AT_TRI_LIGHTACTION_GET_ALL_VALUES             AJ_APP_MESSAGE_ID(6 + NUM_PRECEDING_OBJECTS, 0, AJ_PROP_GET_ALL)
#define DE_AT_TRI_LIGHTACTION_VERSION_PROPERTY           AJ_APP_PROPERTY_ID(6 + NUM_PRECEDING_OBJECTS, 1, 0)
#define DE_AT_TRI_LIGHTACTION_STATES_PROPERTY            AJ_APP_PROPERTY_ID(6 + NUM_PRECEDING_OBJECTS, 1, 1)
#define DE_AT_TRI_LIGHTACTION_OPTPARAMS_PROPERTY         AJ_APP_PROPERTY_ID(6 + NUM_PRECEDING_OBJECTS, 1, 2)
#define DE_AT_TRI_LIGHTACTION_SIGNAL_PROPERTIES_CHANGED  AJ_APP_MESSAGE_ID(6 + NUM_PRECEDING_OBJECTS, 1, 3)
#define DE_AT_TRI_LIGHTACTION_EXEC                       AJ_APP_MESSAGE_ID(6 + NUM_PRECEDING_OBJECTS, 1, 4)

#define EN_TRI_LIGHTCONFIRM_GET_VALUE                  AJ_APP_MESSAGE_ID(7 + NUM_PRECEDING_OBJECTS, 0, AJ_PROP_GET)
#define EN_TRI_LIGHTCONFIRM_SET_VALUE                  AJ_APP_MESSAGE_ID(7 + NUM_PRECEDING_OBJECTS, 0, AJ_PROP_SET)
#define EN_TRI_LIGHTCONFIRM_GET_ALL_VALUES             AJ_APP_MESSAGE_ID(7 + NUM_PRECEDING_OBJECTS, 0, AJ_PROP_GET_ALL)
#define EN_TRI_LIGHTCONFIRM_VERSION_PROPERTY           AJ_APP_PROPERTY_ID(7 + NUM_PRECEDING_OBJECTS, 1, 0)
#define EN_TRI_LIGHTCONFIRM_STATES_PROPERTY            AJ_APP_PROPERTY_ID(7 + NUM_PRECEDING_OBJECTS, 1, 1)
#define EN_TRI_LIGHTCONFIRM_OPTPARAMS_PROPERTY         AJ_APP_PROPERTY_ID(7 + NUM_PRECEDING_OBJECTS, 1, 2)
#define EN_TRI_LIGHTCONFIRM_SIGNAL_PROPERTIES_CHANGED  AJ_APP_MESSAGE_ID(7 + NUM_PRECEDING_OBJECTS, 1, 3)
#define EN_TRI_LIGHTCONFIRM_MESSAGE_PROPERTY           AJ_APP_PROPERTY_ID(7 + NUM_PRECEDING_OBJECTS, 1, 4)
#define EN_TRI_LIGHTCONFIRM_NUM_ACTIONS_PROPERTY       AJ_APP_PROPERTY_ID(7 + NUM_PRECEDING_OBJECTS, 1, 5)
#define EN_TRI_LIGHTCONFIRM_EXEC_ACTION1               AJ_APP_MESSAGE_ID(7 + NUM_PRECEDING_OBJECTS, 1, 6)
#define EN_TRI_LIGHTCONFIRM_EXEC_ACTION2               AJ_APP_MESSAGE_ID(7 + NUM_PRECEDING_OBJECTS, 1, 7)
#define EN_TRI_LIGHTCONFIRM_EXEC_ACTION3               AJ_APP_MESSAGE_ID(7 + NUM_PRECEDING_OBJECTS, 1, 8)

#define DE_AT_TRI_LIGHTCONFIRM_GET_VALUE                  AJ_APP_MESSAGE_ID(8 + NUM_PRECEDING_OBJECTS, 0, AJ_PROP_GET)
#define DE_AT_TRI_LIGHTCONFIRM_SET_VALUE                  AJ_APP_MESSAGE_ID(8 + NUM_PRECEDING_OBJECTS, 0, AJ_PROP_SET)
#define DE_AT_TRI_LIGHTCONFIRM_GET_ALL_VALUES             AJ_APP_MESSAGE_ID(8 + NUM_PRECEDING_OBJECTS, 0, AJ_PROP_GET_ALL)
#define DE_AT_TRI_LIGHTCONFIRM_VERSION_PROPERTY           AJ_APP_PROPERTY_ID(8 + NUM_PRECEDING_OBJECTS, 1, 0)
#define DE_AT_TRI_LIGHTCONFIRM_STATES_PROPERTY            AJ_APP_PROPERTY_ID(8 + NUM_PRECEDING_OBJECTS, 1, 1)
#define DE_AT_TRI_LIGHTCONFIRM_OPTPARAMS_PROPERTY         AJ_APP_PROPERTY_ID(8 + NUM_PRECEDING_OBJECTS, 1, 2)
#define DE_AT_TRI_LIGHTCONFIRM_SIGNAL_PROPERTIES_CHANGED  AJ_APP_MESSAGE_ID(8 + NUM_PRECEDING_OBJECTS, 1, 3)
#define DE_AT_TRI_LIGHTCONFIRM_MESSAGE_PROPERTY           AJ_APP_PROPERTY_ID(8 + NUM_PRECEDING_OBJECTS, 1, 4)
#define DE_AT_TRI_LIGHTCONFIRM_NUM_ACTIONS_PROPERTY       AJ_APP_PROPERTY_ID(8 + NUM_PRECEDING_OBJECTS, 1, 5)
#define DE_AT_TRI_LIGHTCONFIRM_EXEC_ACTION1               AJ_APP_MESSAGE_ID(8 + NUM_PRECEDING_OBJECTS, 1, 6)
#define DE_AT_TRI_LIGHTCONFIRM_EXEC_ACTION2               AJ_APP_MESSAGE_ID(8 + NUM_PRECEDING_OBJECTS, 1, 7)
#define DE_AT_TRI_LIGHTCONFIRM_EXEC_ACTION3               AJ_APP_MESSAGE_ID(8 + NUM_PRECEDING_OBJECTS, 1, 8)

#define TRI_NOTIFICATION_ACTION_AREYOUSURE_GET_VALUE                  AJ_APP_MESSAGE_ID(9 + NUM_PRECEDING_OBJECTS, 0, AJ_PROP_GET)
#define TRI_NOTIFICATION_ACTION_AREYOUSURE_SET_VALUE                  AJ_APP_MESSAGE_ID(9 + NUM_PRECEDING_OBJECTS, 0, AJ_PROP_SET)
#define TRI_NOTIFICATION_ACTION_AREYOUSURE_GET_ALL_VALUES             AJ_APP_MESSAGE_ID(9 + NUM_PRECEDING_OBJECTS, 0, AJ_PROP_GET_ALL)
#define TRI_NOTIFICATION_ACTION_AREYOUSURE_VERSION_PROPERTY           AJ_APP_PROPERTY_ID(9 + NUM_PRECEDING_OBJECTS, 1, 0)
#define TRI_NOTIFICATION_ACTION_AREYOUSURE_SIGNAL_DISMISS             AJ_APP_MESSAGE_ID(9 + NUM_PRECEDING_OBJECTS, 1, 1)

#define EN_TRI_AREYOUSURE_GET_VALUE                  AJ_APP_MESSAGE_ID(10 + NUM_PRECEDING_OBJECTS, 0, AJ_PROP_GET)
#define EN_TRI_AREYOUSURE_SET_VALUE                  AJ_APP_MESSAGE_ID(10 + NUM_PRECEDING_OBJECTS, 0, AJ_PROP_SET)
#define EN_TRI_AREYOUSURE_GET_ALL_VALUES             AJ_APP_MESSAGE_ID(10 + NUM_PRECEDING_OBJECTS, 0, AJ_PROP_GET_ALL)
#define EN_TRI_AREYOUSURE_VERSION_PROPERTY           AJ_APP_PROPERTY_ID(10 + NUM_PRECEDING_OBJECTS, 1, 0)
#define EN_TRI_AREYOUSURE_STATES_PROPERTY            AJ_APP_PROPERTY_ID(10 + NUM_PRECEDING_OBJECTS, 1, 1)
#define EN_TRI_AREYOUSURE_OPTPARAMS_PROPERTY         AJ_APP_PROPERTY_ID(10 + NUM_PRECEDING_OBJECTS, 1, 2)
#define EN_TRI_AREYOUSURE_SIGNAL_PROPERTIES_CHANGED  AJ_APP_MESSAGE_ID(10 + NUM_PRECEDING_OBJECTS, 1, 3)
#define EN_TRI_AREYOUSURE_MESSAGE_PROPERTY           AJ_APP_PROPERTY_ID(10 + NUM_PRECEDING_OBJECTS, 1, 4)
#define EN_TRI_AREYOUSURE_NUM_ACTIONS_PROPERTY       AJ_APP_PROPERTY_ID(10 + NUM_PRECEDING_OBJECTS, 1, 5)
#define EN_TRI_AREYOUSURE_EXEC_ACTION1               AJ_APP_MESSAGE_ID(10 + NUM_PRECEDING_OBJECTS, 1, 6)
#define EN_TRI_AREYOUSURE_EXEC_ACTION2               AJ_APP_MESSAGE_ID(10 + NUM_PRECEDING_OBJECTS, 1, 7)
#define EN_TRI_AREYOUSURE_EXEC_ACTION3               AJ_APP_MESSAGE_ID(10 + NUM_PRECEDING_OBJECTS, 1, 8)

#define DE_AT_TRI_AREYOUSURE_GET_VALUE                  AJ_APP_MESSAGE_ID(11 + NUM_PRECEDING_OBJECTS, 0, AJ_PROP_GET)
#define DE_AT_TRI_AREYOUSURE_SET_VALUE                  AJ_APP_MESSAGE_ID(11 + NUM_PRECEDING_OBJECTS, 0, AJ_PROP_SET)
#define DE_AT_TRI_AREYOUSURE_GET_ALL_VALUES             AJ_APP_MESSAGE_ID(11 + NUM_PRECEDING_OBJECTS, 0, AJ_PROP_GET_ALL)
#define DE_AT_TRI_AREYOUSURE_VERSION_PROPERTY           AJ_APP_PROPERTY_ID(11 + NUM_PRECEDING_OBJECTS, 1, 0)
#define DE_AT_TRI_AREYOUSURE_STATES_PROPERTY            AJ_APP_PROPERTY_ID(11 + NUM_PRECEDING_OBJECTS, 1, 1)
#define DE_AT_TRI_AREYOUSURE_OPTPARAMS_PROPERTY         AJ_APP_PROPERTY_ID(11 + NUM_PRECEDING_OBJECTS, 1, 2)
#define DE_AT_TRI_AREYOUSURE_SIGNAL_PROPERTIES_CHANGED  AJ_APP_MESSAGE_ID(11 + NUM_PRECEDING_OBJECTS, 1, 3)
#define DE_AT_TRI_AREYOUSURE_MESSAGE_PROPERTY           AJ_APP_PROPERTY_ID(11 + NUM_PRECEDING_OBJECTS, 1, 4)
#define DE_AT_TRI_AREYOUSURE_NUM_ACTIONS_PROPERTY       AJ_APP_PROPERTY_ID(11 + NUM_PRECEDING_OBJECTS, 1, 5)
#define DE_AT_TRI_AREYOUSURE_EXEC_ACTION1               AJ_APP_MESSAGE_ID(11 + NUM_PRECEDING_OBJECTS, 1, 6)
#define DE_AT_TRI_AREYOUSURE_EXEC_ACTION2               AJ_APP_MESSAGE_ID(11 + NUM_PRECEDING_OBJECTS, 1, 7)
#define DE_AT_TRI_AREYOUSURE_EXEC_ACTION3               AJ_APP_MESSAGE_ID(11 + NUM_PRECEDING_OBJECTS, 1, 8)



extern const char TriRootContainerObjectPath[];
extern const char enTriRootContainerObjectPath[];
extern const char de_ATTriRootContainerObjectPath[];
extern const char enTriHeatPropertyObjectPath[];
extern const char de_ATTriHeatPropertyObjectPath[];
extern const char enTriLightActionObjectPath[];
extern const char de_ATTriLightActionObjectPath[];
extern const char enTriLightConfirmObjectPath[];
extern const char de_ATTriLightConfirmObjectPath[];
extern const char TriAreYouSureObjectPath[];
extern const char enTriAreYouSureObjectPath[];
extern const char de_ATTriAreYouSureObjectPath[];


extern ContainerWidget TriRootContainer;
extern PropertyWidget TriHeatProperty;
extern ActionWidget TriLightAction;
extern DialogWidget TriLightConfirm;
extern DialogWidget TriAreYouSure;


typedef struct {
    const char* sender;
    uint16_t numSignals;
    int32_t signals[MAX_NUM_LANGUAGES];
} SetValueContext;

typedef struct {
    uint8_t signalType;
    int32_t signalId;
} Signal;

typedef struct {
    uint16_t numSignals;
    Signal signals[MAX_NUM_LANGUAGES * 2];
} ExecuteActionContext;
/**
 *
 * @return
 */
void WidgetsInit();

/**
 * Set Value of a property.
 * @param replyMsg - reply message
 * @param propId - id of property being changed
 * @param context - setvaluecontext. can be used to send signals
 * @return status
 */
AJ_Status SetValueProperty(AJ_Message* replyMsg, uint32_t propId, void* context);

/**
 * Execute Action
 * @param msg - the msg for the response
 * @param msgId - the Action being executed
 * @param context - ExecuteActionContext used to send signals as a result of action
 * @return status
 */
AJ_Status ExecuteAction(AJ_Message* msg, uint32_t msgId, ExecuteActionContext* context);


/* Defines and functions for Tester App */
typedef struct {
    uint32_t msgId;
    uint16_t numParams;
    uint16_t param[3];
} CPSTest;

#define NUMBER_OF_TESTS //NUM_TESTS_GO_HERE

#define ALL_REPLY_CASES                //ALL_REPLIES_GO_HERE

void TestsInit(CPSTest* testsToRun);

void* IdentifyMsgOrPropId(uint32_t identifier, uint16_t* widgetType, uint16_t* propType, uint16_t* language);
void* IdentifyMsgOrPropIdForSignal(uint32_t identifier, uint8_t* isProperty);
uint8_t IdentifyRootMsgOrPropId(uint32_t identifier);
AJSVC_ServiceStatus GeneratedMessageProcessor(AJ_BusAttachment* bus, AJ_Message* msg, AJ_Status* msgStatus);

#endif /* CONTROL_GENERATED_H_ */
